version: '3.8'

services:
  private-sessions:
    image: speakeasy-services-image:latest
    container_name: speakeasy-private-sessions
    ports:
      - '3002:3002'
    environment:
      - SERVICE_NAME=private-sessions
      - NODE_ENV=production
      - PORT=3002
      - DATABASE_URL_FILE=/run/secrets/private_sessions_database_url
      - PRIVATE_SESSIONS_API_KEY_FILE=/run/secrets/private_sessions_api_key
    secrets:
      - source: private_sessions_database_url
        target: private_sessions_database_url
      - source: private_sessions_api_key
        target: private_sessions_api_key
    restart: unless-stopped
    networks:
      - speakeasy-services

  trusted-users:
    image: speakeasy-services-image:latest
    container_name: speakeasy-trusted-users
    ports:
      - '3001:3001'
    environment:
      - SERVICE_NAME=trusted-users
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL_FILE=/run/secrets/trusted_users_database_url
      - TRUSTED_USERS_API_KEY_FILE=/run/secrets/trusted_users_api_key
    secrets:
      - source: trusted_users_database_url
        target: trusted_users_database_url
      - source: trusted_users_api_key
        target: trusted_users_api_key
    restart: unless-stopped
    networks:
      - speakeasy-services

  user-keys:
    image: speakeasy-services-image:latest
    container_name: speakeasy-user-keys
    ports:
      - '3004:3004'
    environment:
      - SERVICE_NAME=user-keys
      - NODE_ENV=production
      - PORT=3004
      - DATABASE_URL_FILE=/run/secrets/user_keys_database_url
      - USER_KEYS_API_KEY_FILE=/run/secrets/user_keys_api_key
    secrets:
      - source: user_keys_database_url
        target: user_keys_database_url
      - source: user_keys_api_key
        target: user_keys_api_key
    restart: unless-stopped
    networks:
      - speakeasy-services

secrets:
  database_url:
    external: true
  private_sessions_database_url:
    external: true
  trusted_users_database_url:
    external: true
  user_keys_database_url:
    external: true
  private_sessions_api_key:
    external: true
  trusted_users_api_key:
    external: true
  user_keys_api_key:
    external: true

networks:
  speakeasy-services:
    name: speakeasy-services
