version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: speakeasy-services-postgres
    environment:
      POSTGRES_USER: speakeasy
      POSTGRES_PASSWORD: speakeasy
      POSTGRES_DB: speakeasy
    ports:
      - '5496:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U speakeasy']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - speakeasy-services

  s3ninja:
    image: scireum/s3-ninja:6
    container_name: s3
    restart: always
    ports:
      - '9444:9000'
    environment:
      - S3NINJA_BUCKETS=speakeasy
    volumes:
      - ./s3ninja-data:/home/sirius/data

networks:
  speakeasy-services:
    name: speakeasy-services

volumes:
  postgres_data:
