name: build-and-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/deploy

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Set version
        id: set_version
        run: |
          echo "version=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=min
          outputs: type=docker,dest=${{ github.workspace }}/speakeasy-services-${{ steps.set_version.outputs.version }}.tar
          build-args: |
            EXPO_PUBLIC_BUNDLE_IDENTIFIER=${{ github.sha }}
          tags: |
            speakeasy-services-image:latest
            speakeasy-services-image:${{ steps.set_version.outputs.version }}

      - name: Gzip Docker Image
        run: |
          gzip -c ${{ github.workspace }}/speakeasy-services-${{ steps.set_version.outputs.version }}.tar > ${{ github.workspace }}/speakeasy-services-${{ steps.set_version.outputs.version }}.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: speakeasy-services-tar-gz
          path: ${{ github.workspace }}/speakeasy-services-${{ steps.set_version.outputs.version }}.tar.gz
          retention-days: 1

  push-to-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        environment: [production, keys-production]

    environment: ${{ matrix.environment }}

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: speakeasy-services-tar-gz
          path: ${{ github.workspace }}

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: ${{ github.workspace }}/speakeasy-services-*.tar.gz
          target: /home/speakeasy
          strip_components: 5

      - name: Load Docker Image and Cleanup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e

            # Find most recent tar.gz file
            LATEST_TAR=$(ls -t /home/speakeasy/speakeasy-services-*.tar.gz | head -n1)

            if [ ! -f "${LATEST_TAR}" ]; then
              echo "Error: Docker image file not found"
              exit 1
            fi

            # Load the image
            gunzip -c "${LATEST_TAR}" > "${LATEST_TAR%.gz}"
            docker load < "${LATEST_TAR%.gz}"
            rm -f "${LATEST_TAR%.gz}"

            # Keep only the 3 most recent tar.gz files
            cd /home/speakeasy
            ls -t speakeasy-services-*.tar.gz | tail -n +4 | xargs -r rm

            # Cleanup old Docker images
            # Keep only the 3 most recent versions plus 'latest' tag
            docker images "speakeasy-services-image:*" --format "{{.Tag}}" | \
              grep -v "latest" | sort -r | tail -n +4 | \
              while read -r tag; do
                # Check if any containers are using this image
                if ! docker ps -a --filter ancestor=speakeasy-services-image:$tag -q | grep -q .; then
                  # Only remove if no containers are using it
                  docker rmi speakeasy-services-image:$tag
                else
                  echo "Skipping removal of speakeasy-services-image:$tag - image is in use"
                fi
              done

  deploy-private-sessions:
    runs-on: ubuntu-latest
    needs: push-to-production
    environment: production

    steps:
      - name: Run Database Migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker run --rm \
              -e PRIVATE_SESSIONS_DATABASE_URL="${{ secrets.PRIVATE_SESSIONS_MIGRATION_DATABASE_URL }}" \
              speakeasy-services-image:latest \
              pnpm --filter @speakeasy-services/private-sessions prisma:migrate

      - name: Deploy Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker compose -f /home/speakeasy/app/docker-compose.yaml up -d speakeasy-private-sessions

            # Wait for container to be running and healthy
            echo "Waiting for container to be healthy..."
            for i in {1..30}; do
              HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' speakeasy-private-sessions)
              if [ "$HEALTH_STATUS" = "healthy" ]; then
                echo "Container is healthy"
                exit 0
              fi
              if [ $i -eq 10 ]; then
                echo "Container failed to become healthy"
                docker logs speakeasy-private-sessions
                exit 1
              fi
              sleep 1
            done

      - name: Deploy Worker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Start new worker
            docker compose -f /home/speakeasy/app/docker-compose.yaml up -d speakeasy-private-sessions-worker

            # Wait for container to be running and healthy
            echo "Waiting for container to be healthy..."
            for i in {1..30}; do
              HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' speakeasy-private-sessions-worker)
              if [ "$HEALTH_STATUS" = "healthy" ]; then
                echo "Container is healthy"
                exit 0
              fi
              if [ $i -eq 10 ]; then
                echo "Container failed to become healthy"
                docker logs speakeasy-private-sessions-worker
                exit 1
              fi
              sleep 1
            done

  deploy-trusted-users:
    runs-on: ubuntu-latest
    needs: push-to-production
    environment: production
    #    if: github.ref == 'refs/heads/main' && (contains(github.event.head_commit.modified, 'packages/') || contains(github.event.head_commit.modified, 'services/trusted-users/'))

    steps:
      - name: Run Database Migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker run --rm \
              -e TRUSTED_USERS_DATABASE_URL="${{ secrets.TRUSTED_USERS_MIGRATION_DATABASE_URL }}" \
              speakeasy-services-image:latest \
              pnpm --filter @speakeasy-services/trusted-users prisma:migrate

      - name: Deploy Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker compose -f /home/speakeasy/app/docker-compose.yaml up -d speakeasy-trusted-users

            # Wait for container to be running and healthy
            echo "Waiting for container to be healthy..."
            for i in {1..30}; do
              HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' speakeasy-trusted-users)
              if [ "$HEALTH_STATUS" = "healthy" ]; then
                echo "Container is healthy"
                exit 0
              fi
              if [ $i -eq 10 ]; then
                echo "Container failed to become healthy"
                docker logs speakeasy-trusted-users
                exit 1
              fi
              sleep 1
            done

  deploy-admin:
    runs-on: ubuntu-latest
    needs: push-to-production
    environment: production
    #    if: github.ref == 'refs/heads/main' && (contains(github.event.head_commit.modified, 'packages/') || contains(github.event.head_commit.modified, 'services/trusted-users/'))

    steps:
      - name: Run Database Migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker run --rm \
              -e SERVICE_ADMIN_DATABASE_URL="${{ secrets.SERVICE_ADMIN_MIGRATION_DATABASE_URL }}" \
              speakeasy-services-image:latest \
              pnpm --filter @speakeasy-services/service-admin prisma:migrate

      - name: Deploy Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker compose -f /home/speakeasy/app/docker-compose.yaml up -d speakeasy-service-admin

            # Wait for container to be running and healthy
            echo "Waiting for container to be healthy..."
            for i in {1..30}; do
              HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' speakeasy-service-admin)
              if [ "$HEALTH_STATUS" = "healthy" ]; then
                echo "Container is healthy"
                exit 0
              fi
              if [ $i -eq 10 ]; then
                echo "Container failed to become healthy"
                docker logs speakeasy-service-admin
                exit 1
              fi
              sleep 1
            done

  deploy-user-keys:
    runs-on: ubuntu-latest
    needs: push-to-production
    environment: keys-production
    #    if: github.ref == 'refs/heads/main' && (contains(github.event.head_commit.modified, 'packages/') || contains(github.event.head_commit.modified, 'services/user-keys/'))

    steps:
      - name: Run Database Migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker run --rm \
              --network db_speakeasy-internal \
              -e USER_KEYS_DATABASE_URL="${{ secrets.USER_KEYS_MIGRATION_DATABASE_URL }}" \
              speakeasy-services-image:latest \
              pnpm --filter @speakeasy-services/user-keys prisma:migrate

      - name: Deploy Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker compose -f /home/speakeasy/app/docker-compose.yaml up -d speakeasy-user-keys

            # Wait for container to be running and healthy
            echo "Waiting for container to be healthy..."
            for i in {1..30}; do
              HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' speakeasy-user-keys)
              if [ "$HEALTH_STATUS" = "healthy" ]; then
                echo "Container is healthy"
                exit 0
              fi
              if [ $i -eq 10 ]; then
                echo "Container failed to become healthy"
                docker logs speakeasy-user-keys
                exit 1
              fi
              sleep 1
            done

      - name: Deploy Worker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Start new worker
            docker compose -f /home/speakeasy/app/docker-compose.yaml up -d user-keys-worker

            # Wait for container to be running and healthy
            echo "Waiting for container to be healthy..."
            for i in {1..30}; do
              HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' speakeasy-user-keys-worker)
              if [ "$HEALTH_STATUS" = "healthy" ]; then
                echo "Container is healthy"
                exit 0
              fi
              if [ $i -eq 10 ]; then
                echo "Container failed to become healthy"
                docker logs speakeasy-user-keys-worker
                exit 1
              fi
              sleep 1
            done
